name: Push component to https://components.espressif.com
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "mcp3002"
          directories: components/mcp3002
          namespace: "nopnop2002"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}